---
AWSTemplateFormatVersion: '2010-09-09'

Description: IAM Policies, and SageMaker Notebook to work with Amazon Comprehend, it will also clone the Lab codebase into the Notebook before you get started.

Parameters:

  EEAssetsBucket:
    Description: "Region-specific assets S3 bucket name (e.g. ee-assets-prod-us-east-1)"
    Type: String

  EEAssetsKeyPrefix:
    Description: "S3 key prefix where this modules assets are stored. (e.g. modules/my_module/v1/)"
    Type: String

  NotebookName:
    Type: String
    Default: AIM317WorkshopNotebook
    Description: Enter the name of the SageMaker notebook instance. Deafault is ComprehendLabNotebook.
    
  InstanceType:
    Type: String
    Default: ml.t2.medium
    AllowedValues:
      - ml.t2.medium
      - ml.m4.xlarge
      - ml.c5.xlarge
      - ml.p2.xlarge
      - ml.p3.2xlarge
    Description: Enter instance type. Default is ml.t2.medium.

  VolumeSize:
    Type: Number
    Default: 20
    MinValue: 5
    MaxValue: 16384
    ConstraintDescription: Must be an integer between 5 (GB) and 16384 (16 TB).
    Description: Enter the size of the EBS volume in GB. Default is 10 GB.

Resources:
  WorkshopRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: ih-ea-poc-workshop
      RepositoryDescription: CodeCommit Repo for the EA Marketplace PoC workshops
      Code:
        S3:
          Bucket: !Ref EEAssetsBucket
          Key: !Sub ${EEAssetsKeyPrefix}intelligenthelpeaPOC.zip


  # SageMaker Execution Role
  SageMakerIamRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"
        - "arn:aws:iam::aws:policy/AWSCodeCommitFullAccess"
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        - "arn:aws:iam::aws:policy/ComprehendFullAccess"
        - "arn:aws:iam::aws:policy/IAMFullAccess"
        - "arn:aws:iam::aws:policy/TranslateFullAccess"
        - "arn:aws:iam::aws:policy/AmazonTranscribeFullAccess"
        
  # SageMaker notebook
  NotebookInstance:
    Type: "AWS::SageMaker::NotebookInstance"
    Properties:
      InstanceType: !Ref InstanceType
      NotebookInstanceName: !Ref NotebookName
      RoleArn: !GetAtt SageMakerIamRole.Arn
      VolumeSizeInGB: !Ref VolumeSize
      DefaultCodeRepository: !GetAtt WorkshopRepository.CloneUrlHttp
      LifecycleConfigName: !GetAtt NotebookInstanceLifecycleConfig.NotebookInstanceLifecycleConfigName

  
  NotebookInstanceLifecycleConfig:
    Type: "AWS::SageMaker::NotebookInstanceLifecycleConfig"
    Properties:
      OnStart:
        - Content:
            Fn::Base64: !Sub |
              #!/bin/bash
              set -e
              mkdir -p /home/ec2-user/SageMaker/data/
              wget https://${EEAssetsBucket}.s3.amazonaws.com/${EEAssetsKeyPrefix}intelligenthelpeaPOCdata.zip && unzip intelligenthelpeaPOCdata.zip -d /home/ec2-user/SageMaker/data/

Outputs:
  WorkshopCloneUrlHttp:
    Description: Workshop CodeCommit Respository Http Clone Url
    Value: !GetAtt WorkshopRepository.CloneUrlHttp 

  WorkshopCloneUrlSsh:
    Description: Workshop CodeCommit Repository SSH Clone Url
    Value: !GetAtt WorkshopRepository.CloneUrlSsh

  WorkshopRepositoryArn:
    Description: Workshop CodeCommit Repository Arn
    Value: !GetAtt WorkshopRepository.Arn          
